import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import IconButton, { IconButtonProps } from "@mui/material/IconButton";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import {
  ImageList,
  Typography,
  ImageListItem,
  Card,
  Box,
  Grid,
  Button,
  CardContent,
  CardMedia,
  TextField,
  Link,
} from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const itemData = [
  {
    img: "Images/Rectangle1.jpg",
    title: "Bed",
  },
  {
    img: "Images/Rectangle4.png",
    title: "Books",
  },
  {
    img: "Images/Rectangle5.png",
    title: "Sink",
  },
  {
    img: "Images/Rectangle2.png",
    title: "Kitchen",
  },
  {
    img: "Images/Rectangle3.png",
    title: "Blinds",
  },
  {
    img: "Images/Rectangle6.png",
    title: "Chairs",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Figma Design 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid className="Header">
          <Typography
            style={{
              position: "absolute",
              left: "110px",
              top: "80px",
              fontWeight: "bolder",
              fontSize: "20px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            LOGO
          </Typography>
          <Grid
            container
            item
            xs={4}
            style={{
              position: "absolute",
              left: "893px",
              top: "85px",
              textAlign: "center",
              fontSize: "20px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            <Grid item xs={3}>
              <Link underline="hover" color={"white"}>
                HOME
              </Link>
            </Grid>
            <Grid item xs={3}>
              <Link underline="hover" color={"white"}>
                PORTFOLIO
              </Link>
            </Grid>
            <Grid item xs={3}>
              <Link underline="hover" color={"white"}>
                ABOUT
              </Link>
            </Grid>
            <Grid item xs={3}>
              <Link underline="hover" color={"white"}>
                CONTACT
              </Link>
            </Grid>
          </Grid>
          <Typography
            style={{
              position: "absolute",
              left: "110px",
              top: "253px",
              fontSize: "24px",
              width: "650px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum
            dolor sit amet, consectetur adipiscing elit.
          </Typography>
          <Image
            alt="HeaderRight"
            src="/HeaderRight.jpg" // Update the path to your image
            layout="fixed"
            width={490}
            height={530}
            style={{
              position: "absolute",
              top: "215px",
              left: "1028px",
            }}
          />
          <Image
            alt="HeaderLeft"
            src="/HeaderLeft.png" // Update the path to your image
            layout="fixed"
            width={520}
            height={540}
            style={{
              position: "absolute",
              top: "544px",
              right: "1000px",
            }}
          />
          <Typography
            style={{
              position: "absolute",
              left: "165px",
              top: "275px",
              fontSize: "309px",
              fontFamily: "Playfair Display, serif",
              fontWeight: "bold",
            }}
          >
            Creative
          </Typography>
          <Typography
            style={{
              position: "absolute",
              left: "305px",
              top: "524px",
              fontSize: "285px",
              fontFamily: "Playfair Display, serif",
              fontWeight: "bold",
            }}
          >
            Design
          </Typography>
          <Button
            variant="contained"
            style={{
              position: "absolute",
              left: "770px",
              top: "978px",
              fontSize: "38px",
              fontFamily: "Inter, sans-serif",
              backgroundColor: "white",
              color: "black",
            }}
          >
            Get a Quote
          </Button>
        </Grid>
        <Grid className="Portfolio">
          <Typography
            style={{
              position: "absolute",
              left: "597px",
              top: "1292px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            Portfolio
          </Typography>
          <ImageList
            variant="masonry"
            cols={2}
            gap={100}
            style={{ position: "absolute", top: "1472px", left: "145px" }}
          >
            {itemData.map((item) => (
              <ImageListItem key={item.img}>
                <img
                  srcSet={`${item.img}?w=248&fit=crop&auto=format&dpr=2 2x`}
                  src={`${item.img}?w=248&fit=crop&auto=format`}
                  alt={item.title}
                  loading="lazy"
                />
              </ImageListItem>
            ))}
          </ImageList>
        </Grid>
        <Grid className="About">
          <Typography
            style={{
              position: "absolute",
              left: "660px",
              top: "4637px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            About
          </Typography>
          <Typography
            style={{
              position: "absolute",
              left: "116px",
              top: "4900px",
              fontSize: "40px",
              width: "600px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            We create stunning Lorem ipsum dolor sit amet, consectetur
            adipiscing elit.We create stunning Lorem ipsum dolor sit amet,
            consectetur adipiscing elit. After 10 years of experience Lorem
            ipsum dolor sit amet, consectetur adipiscing elit.We create stunning
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.We create
            stunning Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </Typography>
          <Image
            alt="About"
            src="/About.png" // Update the path to your image
            layout="fixed"
            width={630}
            height={940}
            style={{
              position: "absolute",
              top: "4816px",
              left: "821px",
            }}
          />
        </Grid>
        <Grid className="Testimonials">
          <Typography
            style={{
              position: "absolute",
              left: "529px",
              top: "6000px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            Testimonials
          </Typography>
          <Typography
            style={{
              position: "absolute",
              left: "203px",
              top: "6150px",
              fontSize: "22px",
              width: "1080px",
              textAlign: "center",
              fontFamily: "Inter, sans-serif",
            }}
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum
            dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit
            amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet,
            consectetur adipiscing elit.
          </Typography>
          <Card
            sx={{
              display: "flex",
              width: "757px",
              height: "309px",
              position: "absolute",
              top: "6400px",
              left: "193px",
            }}
          >
            <CardMedia
              component="img"
              sx={{ width: "309px", height: "327px" }}
              image="Person1.png"
              alt="Live from space album cover"
            />
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                backgroundColor: "rgba(24, 24, 24, 1)",
              }}
            >
              <CardContent sx={{ flex: "1 0 auto" }}>
                <Typography
                  style={{
                    fontSize: "44px",
                    width: "417px",
                    fontFamily: "Inter, sans-serif",
                    fontWeight: "bolder",
                    lineHeight: "1",
                    color: "white",
                  }}
                >
                  “Amazing Team with Lorem Ipsum”
                </Typography>
                <Typography
                  style={{
                    fontSize: "15px",
                    width: "285px",
                    fontFamily: "Inter, sans-serif",
                    fontWeight: "lighter",
                    color: "white",
                    marginTop: "30px",
                  }}
                >
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem
                  ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
                  dolor sit amet,
                </Typography>
                <Typography
                  style={{
                    fontSize: "16px",
                    width: "113px",
                    fontFamily: "Inter, sans-serif",
                    color: "white",
                    marginTop: "49px",
                  }}
                >
                  See full review
                </Typography>
                <IconButton
                  aria-label="See more"
                  style={{
                    color: "white",
                    marginLeft: "105px",
                    marginTop: "-45px",
                  }}
                >
                  <ArrowForwardIcon />
                </IconButton>
              </CardContent>
            </Box>
          </Card>
          <Card
            sx={{
              display: "flex",
              width: "757px",
              height: "309px",
              position: "absolute",
              top: "6780px",
              left: "193px",
            }}
          >
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                backgroundColor: "rgba(24, 24, 24, 1)",
              }}
            >
              <CardContent sx={{ flex: "1 0 auto" }}>
                <Typography
                  style={{
                    fontSize: "44px",
                    width: "417px",
                    fontFamily: "Inter, sans-serif",
                    fontWeight: "bolder",
                    lineHeight: "1",
                    color: "white",
                  }}
                >
                  “Big Dreams for lorem ipsum”
                </Typography>
                <Typography
                  style={{
                    fontSize: "15px",
                    width: "285px",
                    fontFamily: "Inter, sans-serif",
                    fontWeight: "lighter",
                    color: "white",
                    marginTop: "30px",
                  }}
                >
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem
                  ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
                  dolor sit amet,
                </Typography>
                <Typography
                  style={{
                    fontSize: "16px",
                    width: "113px",
                    fontFamily: "Inter, sans-serif",
                    color: "white",
                    marginTop: "49px",
                  }}
                >
                  See full review
                </Typography>
                <IconButton
                  aria-label="See more"
                  style={{
                    color: "white",
                    marginLeft: "105px",
                    marginTop: "-45px",
                  }}
                >
                  <ArrowForwardIcon />
                </IconButton>
              </CardContent>
            </Box>
            <CardMedia
              component="img"
              sx={{ width: "309px", height: "327px" }}
              image="Person2.png"
              alt="Live from space album cover"
            />
          </Card>
          <Card
            sx={{
              maxWidth: "309px",
              maxHeight: "690px",
              position: "absolute",
              top: "6400px",
              left: "1005px",
            }}
          >
            <CardMedia
              component="img"
              sx={{ width: "309px", height: "327px" }}
              image="Person3.png"
              alt="green iguana"
            />
            <CardContent style={{ backgroundColor: "rgba(24, 24, 24, 1)" }}>
              <Typography
                style={{
                  fontSize: "44px",
                  width: "300px",
                  fontFamily: "Inter, sans-serif",
                  fontWeight: "bolder",
                  lineHeight: "1",
                  color: "white",
                }}
              >
                “Good Dreams for lorem ipsum”
              </Typography>
              <Typography
                style={{
                  fontSize: "15px",
                  width: "220px",
                  fontFamily: "Inter, sans-serif",
                  fontWeight: "lighter",
                  color: "white",
                  marginTop: "30px",
                }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem
                ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
                dolor sit amet,
              </Typography>
              <Typography
                style={{
                  fontSize: "16px",
                  width: "113px",
                  fontFamily: "Inter, sans-serif",
                  color: "white",
                  marginTop: "30px",
                }}
              >
                See full review
              </Typography>
              <IconButton
                aria-label="See more"
                style={{
                  color: "white",
                  marginLeft: "105px",
                  marginTop: "-45px",
                }}
              >
                <ArrowForwardIcon />
              </IconButton>
            </CardContent>
          </Card>
          <Button
            variant="outlined"
            style={{
              position: "absolute",
              left: "641px",
              top: "7200px",
              fontSize: "38px",
              fontFamily: "Inter, sans-serif",
              color: "white",
            }}
          >
            See all review
          </Button>
        </Grid>
        <Grid className="About">
          <Typography
            style={{
              position: "absolute",
              left: "620px",
              top: "7550px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            Contact
          </Typography>
          <Grid
            style={{
              position: "absolute",
              left: "329px",
              top: "7700px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            <Typography
              style={{
                fontSize: "55px",
                fontFamily: "Inter, sans-serif",
              }}
            >
              Name
            </Typography>
            <TextField
              id="filled-textarea"
              placeholder="John Doe"
              multiline
              variant="filled"
              style={{
                width: "855px",
                borderBottom: "groove",
              }}
              InputProps={{
                style: {
                  color: "white", // Đặt màu chữ thành màu trắng
                  fontSize: "25px",
                },
              }}
            />
          </Grid>
          <Grid
            style={{
              position: "absolute",
              left: "329px",
              top: "7900px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            <Typography
              style={{
                fontSize: "55px",
                fontFamily: "Inter, sans-serif",
              }}
            >
              Email
            </Typography>
            <TextField
              id="filled-textarea"
              placeholder="jhon@email.com"
              multiline
              variant="filled"
              style={{
                width: "855px",
                borderBottom: "groove",
              }}
              InputProps={{
                style: {
                  color: "white", // Đặt màu chữ thành màu trắng
                  fontSize: "25px",
                },
              }}
            />
          </Grid>
          <Grid
            style={{
              position: "absolute",
              left: "329px",
              top: "8100px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            <Typography
              style={{
                fontSize: "55px",
                fontFamily: "Inter, sans-serif",
              }}
            >
              Message
            </Typography>
            <TextField
              id="standard-multiline-static"
              multiline
              rows={4}
              placeholder="Enter your message here..."
              variant="standard"
              style={{
                width: "855px",
                borderBottom: "groove",
              }}
              InputProps={{
                style: {
                  color: "white", // Đặt màu chữ thành màu trắng
                  fontSize: "25px",
                },
              }}
            />
          </Grid>
          <Button
            variant="contained"
            style={{
              position: "absolute",
              left: "327px",
              top: "8450px",
              fontSize: "38px",
              fontFamily: "Inter, sans-serif",
              backgroundColor: "white",
              color: "black",
            }}
          >
            Send
          </Button>
        </Grid>
      </main>
    </>
  );
}
