import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ImageList,
  Typography,
  ImageListItem,
  List,
  ListItem,
  Grid,
  Button,
} from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const itemData = [
  {
    img: "Images/Rectangle1.jpg",
    title: "Bed",
  },
  {
    img: "Images/Rectangle4.png",
    title: "Books",
  },
  {
    img: "Images/Rectangle5.png",
    title: "Sink",
  },
  {
    img: "Images/Rectangle2.png",
    title: "Kitchen",
  },
  {
    img: "Images/Rectangle3.png",
    title: "Blinds",
  },
  {
    img: "Images/Rectangle6.png",
    title: "Chairs",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Figma Design 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid className="Header">
          <Typography
            style={{
              position: "absolute",
              left: "110px",
              top: "80px",
              fontWeight: "bolder",
              fontSize: "20px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            LOGO
          </Typography>
          <Grid
            container
            item
            xs={4}
            style={{
              position: "absolute",
              left: "893px",
              top: "85px",
              textAlign: "center",
              fontSize: "20px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            <Grid item xs={3}>
              HOME
            </Grid>
            <Grid item xs={3}>
              PORTFOLIO
            </Grid>
            <Grid item xs={3}>
              ABOUT
            </Grid>
            <Grid item xs={3}>
              CONTACT
            </Grid>
          </Grid>
          <Typography
            style={{
              position: "absolute",
              left: "110px",
              top: "253px",
              fontSize: "24px",
              width: "650px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum
            dolor sit amet, consectetur adipiscing elit.
          </Typography>
          <Image
            alt="HeaderRight"
            src="/HeaderRight.jpg" // Update the path to your image
            layout="fixed"
            width={490}
            height={530}
            style={{
              position: "absolute",
              top: "215px",
              left: "1028px",
            }}
          />
          <Image
            alt="HeaderLeft"
            src="/HeaderLeft.png" // Update the path to your image
            layout="fixed"
            width={520}
            height={540}
            style={{
              position: "absolute",
              top: "544px",
              right: "1000px",
            }}
          />
          <Typography
            style={{
              position: "absolute",
              left: "165px",
              top: "275px",
              fontSize: "309px",
              fontFamily: "Playfair Display, serif",
              fontWeight: "bold",
            }}
          >
            Creative
          </Typography>
          <Typography
            style={{
              position: "absolute",
              left: "305px",
              top: "524px",
              fontSize: "285px",
              fontFamily: "Playfair Display, serif",
              fontWeight: "bold",
            }}
          >
            Design
          </Typography>
          <Button
            variant="contained"
            style={{
              position: "absolute",
              left: "770px",
              top: "978px",
              fontSize: "38px",
              fontFamily: "Inter, sans-serif",
              backgroundColor: "white",
              color: "black",
            }}
          >
            Get a Quote
          </Button>
        </Grid>
        <Grid className="Portfolio">
          <Typography
            style={{
              position: "absolute",
              left: "597px",
              top: "1292px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            Portfolio
          </Typography>
          <ImageList
            variant="masonry"
            cols={2}
            gap={100}
            style={{ position: "absolute", top: "1472px", left: "145px" }}
          >
            {itemData.map((item) => (
              <ImageListItem key={item.img}>
                <img
                  srcSet={`${item.img}?w=248&fit=crop&auto=format&dpr=2 2x`}
                  src={`${item.img}?w=248&fit=crop&auto=format`}
                  alt={item.title}
                  loading="lazy"
                />
              </ImageListItem>
            ))}
          </ImageList>
        </Grid>
        <Grid className="About">
          <Typography
            style={{
              position: "absolute",
              left: "660px",
              top: "4637px",
              fontSize: "81px",
              fontFamily: "Playfair Display, serif",
            }}
          >
            About
          </Typography>
          <Typography
            style={{
              position: "absolute",
              left: "116px",
              top: "4900px",
              fontSize: "40px",
              width: "600px",
              fontFamily: "Inter, sans-serif",
            }}
          >
            We create stunning Lorem ipsum dolor sit amet, consectetur
            adipiscing elit.We create stunning Lorem ipsum dolor sit amet,
            consectetur adipiscing elit. After 10 years of experience Lorem
            ipsum dolor sit amet, consectetur adipiscing elit.We create stunning
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.We create
            stunning Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </Typography>
          <Image
            alt="About"
            src="/About.png" // Update the path to your image
            layout="fixed"
            width={630}
            height={940}
            style={{
              position: "absolute",
              top: "4816px",
              left: "821px",
            }}
          />
        </Grid>
      </main>
    </>
  );
}
