import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import { Button } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dataContact = [
    "Address: Cam Ranh - Khanh Hoa",
    "Email: nnhsang1420@gmail.com",
    "Phone: 0376354610",
  ];
  const dataDepartment = ["Information Technology"];
  const dataHobbies = ["Game", "Movies", "Music", "Take a photo"];

  return (
    <>
      <Head>
        <title>About Me</title>
        <Button variant="contained">contailned</Button>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ textAlign: "left", display: "flex", flexDirection: "column" }}
      >
        <div style={{ position: "relative", left: "48px" }}>
          <h1>About Me</h1>
        </div>
        <div
          style={{
            display: "flex",
            marginTop: "20px",
            padding: "20px",
          }}
        >
          <div style={{ position: "relative", flex: "0 1 20%" }}>
            <div
              style={{
                position: "absolute",
                top: "-10px",
                left: "48px",
                borderRadius: "50%",
              }}
            >
              <Image
                src="/avt.jpg"
                width={200}
                height={200}
                alt="no image"
                style={{ borderRadius: "50%" }}
              />
            </div>
            <div style={{ position: "absolute", top: "200px", left: "48px" }}>
              <h2>Nguyễn Ngọc Hoài Sang</h2>
            </div>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ display: "flex" }}>
              <div style={{ flex: "0 1 20%" }}>
                <h3>Contact</h3>
                <div style={{ height: "1px", backgroundColor: "gray" }}></div>
                <ul>
                  {dataContact.map((item, index) => (
                    <li key={index} style={{ color: "red" }}>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div style={{ flex: "0 1 15%", marginLeft: "20px" }}>
                <h3>Department</h3>
                <div
                  style={{
                    height: "1px",
                    backgroundColor: "gray",
                    width: "205px",
                  }}
                ></div>
                <div style={{ marginTop: "15px" }}>
                  {dataDepartment.map((item, index) => (
                    <li key={index} style={{ color: "red" }}>
                      {item}
                    </li>
                  ))}
                </div>
              </div>
              <div style={{ flex: "0 1 20%", marginLeft: "20px" }}>
                <h3>Hobbies</h3>
                <div
                  style={{
                    height: "1px",
                    backgroundColor: "gray",
                    width: "145px",
                  }}
                ></div>
                <ul>
                  {dataHobbies.map((item, index) => (
                    <li key={index} style={{ color: "red" }}>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
